local utils = {}

utils.modules = {
    "core.settings",
    "core.autocmds",
    "core.commands",
    "plugins",
}

utils.symbols = {
    -- Text = "   ",
    -- Method = "   ",
    -- Function = "   ",
    -- Constructor = "   ",
    -- Field = "   ",
    -- Variable = "   ",
    -- Class = "   ",
    -- Interface = "   ",
    -- Module = "   ",
    -- Property = "   ",
    -- Unit = "   ",
    -- Value = "   ",
    -- Enum = "   ",
    -- Keyword = "   ",
    -- Snippet = "   ",
    -- Color = "   ",
    -- File = "   ",
    -- Reference = "   ",
    -- Folder = "   ",
    -- Null = "   ",
    -- EnumMember = "   ",
    -- Constant = "   ",
    -- Struct = "   ",
    -- Event = "   ",
    -- Operator = "   ",
    -- TypeParameter = "   ",
    Text = " ",
    Method = " ",
    Function = " ",
    Constructor = " ",
    Field = "ﰠ ",
    Variable = " ",
    Class = "ﴯ ",
    Interface = " ",
    Module = " ",
    Property = "ﰠ ",
    Unit = "塞 ",
    Value = " ",
    Enum = " ",
    Keyword = " ",
    Snippet = " ",
    Color = " ",
    File = " ",
    Reference = " ",
    Folder = " ",
    EnumMember = " ",
    Constant = " ",
    Struct = "פּ ",
    Event = " ",
    Operator = " ",
    TypeParameter = " ",
}

return utils
