require("focus").setup({
    signcolumn = false,
    cursorline = false,
    excluded_buftypes = {
        "help",
        "nowrite",
        "prompt",
        "popup",
        "fugitive",
        "alpha",
    },
    excluded_filetypes = {
        "alpha",
        "help",
        "NvimTree_*",
        "neo-tree",
        "Telescope",
        "TelescopePrompt",
        "ToggleTerm",
        "DiffviewFiles",
        "DiffviewFileHistory",
        "fugitive",
        "DressingInput",
        "gitcommit",
    },
})
