require("indent_blankline").setup({
    space_char_blankline = " ",
    show_current_context = false,
    show_current_context_start = false,
    show_trailing_blankline_indent = false,
    show_first_indent_level = false,
    buftype_exclude = { "help", "terminal", "nofile" },
    filetype_exclude = {
        "startify",
        "dashboard",
        "dotooagenda",
        "log",
        "fugitive",
        "gitcommit",
        "packer",
        "vimwiki",
        "markdown",
        "txt",
        "vista",
        "help",
        "todoist",
        "NvimTree",
        "peekaboo",
        "git",
        "TelescopePrompt",
        "undotree",
        "flutterToolsOutline",
        "", -- for all buffers without a file type
    },
})
